# cloudbuild.yaml

steps:
  # 1) Build image to Container Registry (gcr.io)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/learning-496718/github.com/maxklema/javascript-tetris-2:$COMMIT_SHA'
      - '.'

  # 2) Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/learning-496718/github.com/maxklema/javascript-tetris-2:$COMMIT_SHA'

  # 3) Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'javascript-tetris-2'  # Cloud Run service name
      - '--image'
      - 'gcr.io/learning-496718/github.com/maxklema/javascript-tetris-2:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - 'gcr.io/learning-496718/github.com/maxklema/javascript-tetris-2:$COMMIT_SHA'
